### ISSUE TITLE
Locking Info Dashboard is not working

### ISSUE THREAD

**Issue by waseemakram786** [lefred/innotopgo#19]
Hi Lefred,

I have installed the innotopgo version 0.3 tool and it is very helpful

I was testing all the available dashboards by creating the test scenarios,  the locking info dashboard is not getting switched post giving the input as **<L>**, also it is prompting to provide the thread_id as input, post giving the thread_id, it is failing to fetch the locking details

please help to resolve this issue or let me know if I am missing something.

PFA
<img width="1438" alt="Screenshot 2021-10-27 at 6 14 33 PM" src="https://user-images.githubusercontent.com/58878927/139070475-684ccfaa-0bab-49a9-9ad8-2b9735487770.png">
,

**Comment by lefred** [comment]
version 0.3.1 should be fixed
